CREATE DATABASE IF NOT EXISTS archive_aura DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE archive_aura;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
